


enum{
    DIALOG_HELP,
    DIALOG_GENERALCOMMANDS,
    DIALOG_ROBBERCOMMANDS,
    DIALOG_COPSCOMMANDS,
    DIALOG_SPECIALAGENTCOMMANDS,
    DIALOG_HOUSECOMMANDS,
    DIALOG_CASINOCOMMANDS,
    DIALOG_JOBCOMMANDS,
};