#define COLOR_ALICEBLUE             0xF0F8FFFF
#define COLOR_ANTIQUEWHITE          0xFAEBD7FF
#define COLOR_AQUA                  0x00FFFFFF
#define COLOR_AQUAMARINE            0x7FFFD4FF
#define COLOR_AZURE                 0xF0FFFFFF
#define COLOR_BEIGE                 0xF5F5DCFF
#define COLOR_BISUQE                0XFFE4C4FF
#define COLOR_BLACK                 0X000000FF
#define COLOR_BLENCHEDALMOND        0XFFEBCDFF
#define COLOR_BLUE                  0X0000FFFF
#define COLOR_BLUEVIOLET            0X8A2BE2FF
#define COLOR_BROWN                 0XA52A2AFF
#define COLOR_BURLYWOOD             0XDEB887FF
#define COLOR_CADETBLUE             0X5F9EA0FF
#define COLOR_CHARTREUSE            0X7FFF00FF
#define COLOR_CHOCOLATE             0XD2691EFF
#define COLOR_CORAL                 0XFF7F50FF
#define COLOR_CORNFLOWERBLUE        0X6495EDFF
#define COLOR_CORNSILK              0XFFF8DCFF
#define COLOR_CRIMSON               0XDC143CFF
#define COLOR_CYAN                  0X00FFFFFF
#define COLOR_DARKBLUE              0X00008BFF
#define COLOR_DARKCYAN              0X008B8BFF
#define COLOR_DARKGOLDENROD         0XB8860BFF
#define COLOR_DARKGRAY              0XA9A9A9FF
#define COLOR_DARKGREY              0XA9A9A9FF
#define COLOR_DARKGREEN             0X006400FF
#define COLOR_DARKKHAKI             0XBDB76BFF
#define COLOR_DARKMAGENTA           0X8B008BFF
#define COLOR_DARKOLIVEGREEN        0X556B2FFF
#define COLOR_DARKORANGE            0XFF8C00FF
#define COLOR_DARKORCHID            0X9932CCFF
#define COLOR_DARKRED               0X8B0000FF
#define COLOR_DARKSALMON            0XE9967AFF
#define COLOR_DARKSEAGREEN          0X8FBC8FFF
#define COLOR_DARKSLATEBLUE         0X483D8BFF
#define COLOR_DARKSLATEGRAY         0X2F4F4FFF
#define COLOR_DARKSLATEGREY         0X2F4F4FFF
#define COLOR_DARKTURQUOISE         0x00CED1FF
#define COLOR_DARKVIOLET            0x9400D3FF
#define COLOR_DEEPPINK              0XFF1493FF
#define COLOR_DEEPSKYBLUE           0X00BFFFFF
#define COLOR_DIMGRAY               0X696969FF
#define COLOR_DIMGREY               0X696969FF
#define COLOR_DODGERBLUE            0X1E90FFFF
#define COLOR_FIREBRICK             0XB22222FF
#define COLOR_FLORALWHITE           0XFFFAF0FF
#define COLOR_FORESTGREEN           0X228B22FF
#define COLOR_FUCHSIA               0XFF00FFFF
#define COLOR_GAINSBORO             0XDCDCDCFF
#define COLOR_GHOSTWHITE            0XF8F8FFFF
#define COLOR_GOLD                  0XFFD700FF
#define COLOR_GOLDENROD             0XDAA520FF
#define COLOR_GRAY                  0X808080FF
#define COLOR_GREY                  0X808080FF
#define COLOR_GREEN                 0X008000FF
#define COLOR_GREENYELLOW           0XADFF2FFF
#define COLOR_HONEYDEW              0XF0FFF0FF
#define COLOR_HOTPINK               0XFF69B4FF
#define COLOR_INDIANRED             0XCD5C5CFF
#define COLOR_INDIGO                0X4B0082FF
#define COLOR_IVORY                 0XFFFFF0FF
#define COLOR_KHAKI                 0XF0E68CFF
#define COLOR_LAVENDER              0XE6E6FAFF
#define COLOR_LAVENDERBLUSH         0XFFF0F5FF
#define COLOR_LAWNGREEN             0X7CFC00FF
#define COLOR_LEMONCHIFFON          0XFFFACDFF
#define COLOR_LIGHTBLUE             0XADD8E6FF
#define COLOR_LIGHTCORAL            0XF08080FF
#define COLOR_LIGHCYAN              0XE0FFFFFF
#define COLOR_LIGHTGOLDENRODYELLOW  0XFAFAD2FF
#define COLOR_LIGHTGRAY             0X
#define COLOR_LIGHTGREY             0X
#define COLOR_LIGHTGREEN            0X
#define COLOR_LIGHTPINK             0X
#define COLOR_LIGHTSALMON           0X
#define COLOR_LIGHTSEAGREEN         0X         
#define COLOR_LIGHTSKYBLUE          0X
#define COLOR_LIGHTSLATEGRAY        0X
#define COLOR_LIGHTSLATEGREY        0X
#define COLOR_LIGHTSTEELBLUE        0X
#define COLOR_LIGHTYELLOW           0X
#define COLOR_LIME                  0X
#define COLOR_LIMEGREEN             0X
#define COLOR_LINEN                 0X
#define COLOR_MAGENTA               0X
#define COLOR_MAROON                0X
#define COLOR_MEDIUMAQUAMARINE      0X
#define COLOR_MEDIUMBLUE            0X
#define COLOR_MEDIUMORCHID          0X
#define COLOR_MEDIUMPURPLE          0X
#define COLOR_MEDIUMSEAGREEN        0X
#define COLOR_MEDIUEMSLATEBLUE      0X
#define COLOR_MEDIUMSPRINGGREEN     0X
#define COLOR_MEDIUMTURQUOISE       0X
#define COLOR_MEDIUMVIOLETRED       0X
#define COLOR_MIDNIGHTBLUE          0X
#define COLOR_MINTCREAM             0X
#define COLOR_MISTYROSE             0X
#define COLOR_MOCCASIN              0X
#define COLOR_NAVAJOWHITE           0X
#define COLOR_NAVY                  0X
#define COLOR_OLDLACE               0X
#define COLOR_OLIVE                 0X
#define COLOR_OLIVEDRAB             0X
#define COLOR_ORANGE                0X
#define COLOR_ORANGERED             0X
#define COLOR_ORCHID                0X
#define COLOR_PALEGOLDENROD         0X
#define COLOR_PALEGREEN             0X
#define COLOR_PALETURQUOISE         0X
#define COLOR_PALEVIOLETRED         0X
#define COLOR_PAPAYAWHIP            0X
#define COLOR_PEACHPUFF             0X
#define COLOR_PERU                  0X
#define COLOR_PINK                  0X
#define COLOR_PLUM                  0X
#define COLOR_POWDERBLUE            0X
#define COLOR_PURPLE                0X
#define COLOR_REBECCAPURPLE         0X
#define COLOR_RED                   0X
#define COLOR_ROSYBROWN             0X
#define COLOR_ROYALBLUE             0X
#define COLOR_SADDLEBROWN           0X
#define COLOR_SALMON                0X
#define COLOR_SANDYBROWN            0X
#define COLOR_SEAGREEN              0X
#define COLOR_SEASHELL              0X
#define COLOR_SIENNA                0X
#define COLOR_SILVER                0X
#define COLOR_SKYBLUE               0X
#define COLOR_SLATEBLUE             0X
#define COLOR_SLATEGRAY             0X
#define COLOR_SLATEGREY             0X
#define COLOR_SNOW                  0X
#define COLOR_SPRINGGREEN           0X
#define COLOR_STEELBLUE             0X
#define COLOR_TAN                   0X
#define COLOR_TEAL                  0X
#define COLOR_THISTLE               0X
#define COLOR_TOMATO                0X
#define COLOR_TURQUOISE             0X
#define COLOR_VIOLET                0X
#define COLOR_WHEAT                 0X
#define COLOR_WHITE                 0X
#define COLOR_WHITESMOKE            0X
#define COLOR_YELLOW                0X
#define COLOR_YELLOWGREEN           0X