/*
	ABOUT:
	Avernus Cops & Robbers is a gamemode for players who wants to kill time and play with others in
	a welcoming community. A Cops & Robber gamemode offers you a gameplay to play as a Robber or a
	Cop depending on your choice! You have a freedom of choice here! Isn't that great? You can aslo
	play as a Special Agent but you need a certain amount of EXPerience to unlock this class, or if
	you want you can donate and unlock it instantly! This can help the server progress and keep running

	CREDITS:
	Avernus Cops & Robbers is made solely by CodeZulan, made possible thanks to these people:

	///////////////////////////////////
	//  Y_Cole - YSI Library         //
	//  Incognito - Streamer Plugin  //
	//  Maddinat0r - Sscanf2 Plugin  //
	//  Zeex - Crashdetect Plugin    //
	///////////////////////////////////

	MODULE:
	This is the dialogs module and simply enumerates the different dialog ids to be used.
	
*/

enum{

    // HELP SECTION
    DIALOG_HELP,
    DIALOG_GENERALCOMMANDS,
    DIALOG_ROBBERCOMMANDS,
    DIALOG_COPSCOMMANDS,
    DIALOG_SPECIALAGENTCOMMANDS,
    DIALOG_HOUSECOMMANDS,
    DIALOG_CASINOCOMMANDS,
    DIALOG_JOBCOMMANDS,
    
};